interval: 15s
providers:
  currencyConverter: ~
  openExchangeRates:
    app_key: "<PASTE YOUR KEY HERE>"
currencies:
  - from: USD
    to: PLN
    provider_name: currencyConverter
    alert:
      any_change: true
  - from: EUR
    to: PLN
    provider_name: currencyConverter
    alert:
      any_change: true
